import { useMemo, useState } from 'react'
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, IconButton, MenuItem, Paper, Stack, Tab, Tabs, TextField, Typography } from '@mui/material'
import { Archive, ArrowBack, ArrowForward, AssignmentTurnedIn, CancelRounded, CheckCircleRounded, DeleteOutline, Edit, PersonAdd, PictureAsPdf, ReplayCircleFilledRounded, Restore, Save, School, Science, UploadFile, Visibility } from '@mui/icons-material'
import { useSharedCloudState } from '../services/useSharedCloudState'
import { ONLINE_EXAM_ACCEPT, removeOnlineExamFile, uploadOnlineExamFile, validateOnlineExamFile } from '../services/onlineExamFiles'

const STATE_KEY='private-lessons-v1'
const LOCAL_KEY='taskin-private-lessons-v1'
const POOL_STATE_KEY='private-science-exam-pool-v1'
const POOL_LOCAL_KEY='taskin-private-science-exam-pool-v1'
const emptyStudent={fullName:'',username:'',password:'',address:'',hourlyFee:'',lessonMinutes:60,notes:''}
const emptyExam={name:'',answers:{},attachment:null,archived:false}
const ANSWERS=['A','B','C','D']
const statuses={
  done:{label:'Yapıldı',color:'#166534',bg:'#dcfce7',border:'#86efac',Icon:CheckCircleRounded},
  missed:{label:'Yapılmadı',color:'#991b1b',bg:'#fee2e2',border:'#fca5a5',Icon:CancelRounded},
  makeup:{label:'Telafi',color:'#854d0e',bg:'#fef3c7',border:'#facc15',Icon:ReplayCircleFilledRounded}
}
const pad=n=>String(n).padStart(2,'0')
const dateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`
const money=value=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:2}).format(Number(value||0))
const fmtDate=value=>value?new Date(value).toLocaleString('tr-TR'):'—'
const netOf=(correct,wrong)=>Number(correct||0)-Number(wrong||0)/3
const numeric=v=>Number(v||0)
const sortDate=(a,b)=>new Date(a.date||a.finishedAt||a.endAt||a.createdAt||0)-new Date(b.date||b.finishedAt||b.endAt||b.createdAt||0)
const resultValues=r=>({correct:numeric(r?.correct),wrong:numeric(r?.wrong),blank:numeric(r?.blank),net:Number(r?.net??netOf(r?.correct,r?.wrong))})

function NetLineChart({items}){
  if(!items.length) return <Alert severity="info">Grafik için henüz sonuç yok.</Alert>
  const width=760,height=250,padX=46,padY=32
  const values=items.map(x=>Number(x.net||0))
  const min=Math.min(0,...values),max=Math.max(1,...values)
  const range=Math.max(1,max-min)
  const points=items.map((x,i)=>({x:items.length===1?width/2:padX+i*(width-padX*2)/(items.length-1),y:height-padY-(Number(x.net||0)-min)*(height-padY*2)/range}))
  const poly=points.map(p=>`${p.x},${p.y}`).join(' ')
  return <Box sx={{width:'100%',overflowX:'auto'}}><svg viewBox={`0 0 ${width} ${height}`} style={{width:'100%',minWidth:560,display:'block'}} role="img" aria-label="Son 10 denemenin net çizgi grafiği">
    {[0,.25,.5,.75,1].map(t=>{const y=padY+t*(height-padY*2); const value=max-t*range; return <g key={t}><line x1={padX} x2={width-padX} y1={y} y2={y} stroke="currentColor" opacity=".12"/><text x={8} y={y+4} fontSize="12" fill="currentColor" opacity=".7">{value.toFixed(1)}</text></g>})}
    <polyline points={poly} fill="none" stroke="currentColor" strokeWidth="4" strokeLinejoin="round" strokeLinecap="round"/>
    {points.map((p,i)=><g key={items[i].id||i}><circle cx={p.x} cy={p.y} r="6" fill="currentColor"/><text x={p.x} y={height-8} textAnchor="middle" fontSize="11" fill="currentColor">{i+1}</text><text x={p.x} y={p.y-11} textAnchor="middle" fontSize="12" fontWeight="700" fill="currentColor">{Number(items[i].net).toFixed(2)}</text></g>)}
  </svg></Box>
}

export default function PrivateLessonsPage(){
  const [data,setData,ready]=useSharedCloudState({stateKey:STATE_KEY,localKey:LOCAL_KEY,fallback:{students:[]}})
  const [poolData,setPoolData,poolReady]=useSharedCloudState({stateKey:POOL_STATE_KEY,localKey:POOL_LOCAL_KEY,fallback:{exams:[]}})
  const students=Array.isArray(data?.students)?data.students:[]
  const exams=Array.isArray(poolData?.exams)?poolData.exams:[]
  const [selectedId,setSelectedId]=useState(null)
  const [formOpen,setFormOpen]=useState(false)
  const [form,setForm]=useState(emptyStudent)
  const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1))
  const [dayOpen,setDayOpen]=useState(false)
  const [selectedDate,setSelectedDate]=useState('')
  const [entry,setEntry]=useState({status:'done',payment:'unpaid',durationMinutes:60,note:''})
  const [tab,setTab]=useState(0)
  const [examOpen,setExamOpen]=useState(false)
  const [examForm,setExamForm]=useState(emptyExam)
  const [examFile,setExamFile]=useState(null)
  const [examUploading,setExamUploading]=useState(false)
  const [assignOpen,setAssignOpen]=useState(false)
  const [assignForm,setAssignForm]=useState({examId:'',startAt:'',endAt:''})
  const [resultOpen,setResultOpen]=useState(false)
  const [resultAssignment,setResultAssignment]=useState(null)
  const [schoolOpen,setSchoolOpen]=useState(false)
  const [schoolForm,setSchoolForm]=useState({name:'',date:'',correct:'',wrong:'',net:'',schoolRank:''})
  const [showArchive,setShowArchive]=useState(false)
  const selected=students.find(s=>s.id===selectedId)||students[0]||null

  function saveData(nextStudents){setData({...(data||{}),students:nextStudents})}
  function updateSelected(patch){if(!selected)return; saveData(students.map(s=>s.id===selected.id?{...s,...patch}:s))}
  function savePool(nextExams){setPoolData({...(poolData||{}),exams:nextExams})}
  function openNew(){setForm(emptyStudent);setFormOpen(true)}
  function openEditStudent(student){setSelectedId(student.id);setForm({...emptyStudent,...student});setFormOpen(true)}
  function saveStudent(){
    if(!form.fullName.trim()||!form.username.trim()||!form.password.trim()) return alert('Ad soyad, kullanıcı adı ve şifre zorunludur.')
    const duplicate=students.some(s=>s.id!==form.id&&String(s.username||'').trim().toLowerCase()===form.username.trim().toLowerCase())
    if(duplicate)return alert('Bu kullanıcı adı başka bir öğrencide kullanılıyor.')
    const clean={...form,fullName:form.fullName.trim(),username:form.username.trim(),password:form.password.trim(),address:(form.address||'').trim(),hourlyFee:Number(form.hourlyFee||0),lessonMinutes:Number(form.lessonMinutes||60)}
    if(form.id) saveData(students.map(s=>s.id===form.id?{...s,...clean}:s))
    else {const item={...clean,id:crypto.randomUUID(),lessons:{},examAssignments:[],schoolExams:[]};saveData([...students,item]);setSelectedId(item.id)}
    setFormOpen(false)
  }
  function removeStudent(student){if(!window.confirm(`${student.fullName} ve tüm özel ders kayıtları silinsin mi?`))return;const next=students.filter(s=>s.id!==student.id);saveData(next);if(selected?.id===student.id)setSelectedId(next[0]?.id||null)}
  function openDay(key){if(!selected)return;const old=selected.lessons?.[key];setSelectedDate(key);setEntry(old?{...old}:{status:'done',payment:'unpaid',durationMinutes:selected.lessonMinutes||60,note:''});setDayOpen(true)}
  function saveDay(){const updated={...selected,lessons:{...(selected.lessons||{}),[selectedDate]:{...entry,durationMinutes:Number(entry.durationMinutes||selected.lessonMinutes||60)}}};saveData(students.map(s=>s.id===selected.id?updated:s));setDayOpen(false)}
  function deleteDay(){const lessons={...(selected.lessons||{})};delete lessons[selectedDate];updateSelected({lessons});setDayOpen(false)}

  function openNewExam(){setExamForm(emptyExam);setExamFile(null);setExamOpen(true)}
  function openEditExam(exam){setExamForm({...exam,answers:{...(exam.answers||{})}});setExamFile(null);setExamOpen(true)}
  async function saveExam(){
    if(!examForm.name.trim())return alert('Deneme adı zorunludur.')
    const missing=Array.from({length:20},(_,i)=>i+1).filter(q=>!examForm.answers?.[q]);if(missing.length)return alert(`Cevap anahtarı eksik: ${missing.join(', ')}`)
    const fileError=validateOnlineExamFile(examFile);if(fileError)return alert(fileError)
    setExamUploading(true)
    try{const id=examForm.id||crypto.randomUUID();let attachment=examForm.attachment||null;if(examFile){if(attachment)await removeOnlineExamFile(attachment).catch(()=>{});attachment=await uploadOnlineExamFile(examFile,'private-science',id)}const item={...examForm,id,name:examForm.name.trim(),attachment,archived:Boolean(examForm.archived),updatedAt:new Date().toISOString()};savePool(examForm.id?exams.map(e=>e.id===id?item:e):[...exams,{...item,createdAt:new Date().toISOString()}]);setExamOpen(false)}catch(error){alert(error.message||'Deneme kaydedilemedi.')}finally{setExamUploading(false)}
  }
  function archiveExam(exam){savePool(exams.map(e=>e.id===exam.id?{...e,archived:!e.archived}:e))}
  async function deleteExam(exam){const used=students.some(s=>(s.examAssignments||[]).some(a=>a.examId===exam.id));if(used)return alert('Bu deneme en az bir öğrenciye atanmış. Önce öğrenci atamalarını silmelisin.');if(!window.confirm(`${exam.name} kalıcı olarak silinsin mi?`))return;if(exam.attachment)await removeOnlineExamFile(exam.attachment).catch(()=>{});savePool(exams.filter(e=>e.id!==exam.id))}

  function openAssign(){const first=exams.find(e=>!e.archived);setAssignForm({examId:first?.id||'',startAt:'',endAt:''});setAssignOpen(true)}
  function assignExam(){if(!assignForm.examId||!assignForm.startAt||!assignForm.endAt)return alert('Deneme, başlangıç ve bitiş zamanı zorunludur.');if(new Date(assignForm.endAt)<=new Date(assignForm.startAt))return alert('Bitiş zamanı başlangıçtan sonra olmalıdır.');const assignment={id:crypto.randomUUID(),examId:assignForm.examId,startAt:assignForm.startAt,endAt:assignForm.endAt,status:'active',answers:{},result:null,archived:false,createdAt:new Date().toISOString()};updateSelected({examAssignments:[...(selected.examAssignments||[]),assignment]});setAssignOpen(false)}
  function editAssignment(a){setAssignForm({assignmentId:a.id,examId:a.examId,startAt:a.startAt,endAt:a.endAt});setAssignOpen(true)}
  function saveAssignmentEdit(){if(!assignForm.examId||!assignForm.startAt||!assignForm.endAt)return alert('Tüm alanlar zorunludur.');if(new Date(assignForm.endAt)<=new Date(assignForm.startAt))return alert('Bitiş zamanı başlangıçtan sonra olmalıdır.');updateSelected({examAssignments:(selected.examAssignments||[]).map(a=>a.id===assignForm.assignmentId?{...a,examId:assignForm.examId,startAt:assignForm.startAt,endAt:assignForm.endAt}:a)});setAssignOpen(false)}
  function cancelResult(a){if(!window.confirm('Sonuç silinsin ve deneme öğrenci ekranında tekrar aktif olsun mu?'))return;updateSelected({examAssignments:(selected.examAssignments||[]).map(x=>x.id===a.id?{...x,status:'active',answers:{},result:null,finishedAt:null,startedAt:null,archived:false}:x)})}
  function archiveAssignment(a){updateSelected({examAssignments:(selected.examAssignments||[]).map(x=>x.id===a.id?{...x,archived:!x.archived}:x)})}
  function deleteAssignment(a){if(!window.confirm('Bu deneme ataması kalıcı olarak silinsin mi?'))return;updateSelected({examAssignments:(selected.examAssignments||[]).filter(x=>x.id!==a.id)})}
  function showResult(a){setResultAssignment(a);setResultOpen(true)}

  function openSchool(item=null){setSchoolForm(item?{...item}:{name:'',date:'',correct:'',wrong:'',net:'',schoolRank:''});setSchoolOpen(true)}
  function saveSchool(){if(!schoolForm.name.trim()||!schoolForm.date)return alert('Deneme adı ve tarih zorunludur.');const correct=numeric(schoolForm.correct),wrong=numeric(schoolForm.wrong);const item={...schoolForm,id:schoolForm.id||crypto.randomUUID(),name:schoolForm.name.trim(),correct,wrong,net:schoolForm.net===''?netOf(correct,wrong):Number(schoolForm.net),schoolRank:numeric(schoolForm.schoolRank)};const list=schoolForm.id?(selected.schoolExams||[]).map(x=>x.id===item.id?item:x):[...(selected.schoolExams||[]),item];updateSelected({schoolExams:list});setSchoolOpen(false)}
  function deleteSchool(id){if(!window.confirm('Okul denemesi silinsin mi?'))return;updateSelected({schoolExams:(selected.schoolExams||[]).filter(x=>x.id!==id)})}

  async function exportPdf(){
    if(!selected)return
    const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))
    const rows=allResults.map((x,i)=>`<tr><td>${i+1}</td><td>${escapeHtml(x.type)}</td><td>${escapeHtml(x.name)}</td><td>${x.correct}</td><td>${x.wrong}</td><td>${x.blank}</td><td>${Number(x.net).toFixed(2)}</td><td>${x.schoolRank||'—'}</td></tr>`).join('')
    const chartItems=lastTen
    let chartHtml='<div class="empty">Grafik için henüz sonuç yok.</div>'
    if(chartItems.length){
      const width=720,height=230,padX=48,padY=30
      const values=chartItems.map(x=>Number(x.net||0)),min=Math.min(0,...values),max=Math.max(1,...values),range=Math.max(1,max-min)
      const points=chartItems.map((x,i)=>({x:chartItems.length===1?width/2:padX+i*(width-padX*2)/(chartItems.length-1),y:height-padY-(Number(x.net||0)-min)*(height-padY*2)/range,value:Number(x.net||0)}))
      const grid=[0,.25,.5,.75,1].map(t=>{const y=padY+t*(height-padY*2),value=max-t*range;return `<line x1="${padX}" x2="${width-padX}" y1="${y}" y2="${y}" stroke="#e5e7eb"/><text x="4" y="${y+4}" font-size="11" fill="#6b7280">${value.toFixed(1)}</text>`}).join('')
      const dots=points.map((p,i)=>`<circle cx="${p.x}" cy="${p.y}" r="5" fill="#ea580c"/><text x="${p.x}" y="${p.y-10}" text-anchor="middle" font-size="11" font-weight="700" fill="#111827">${p.value.toFixed(2)}</text><text x="${p.x}" y="${height-5}" text-anchor="middle" font-size="10" fill="#6b7280">${i+1}</text>`).join('')
      chartHtml=`<svg viewBox="0 0 ${width} ${height}" width="100%" xmlns="http://www.w3.org/2000/svg">${grid}<polyline points="${points.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" stroke="#ea580c" stroke-width="4" stroke-linejoin="round" stroke-linecap="round"/>${dots}</svg>`
    }
    const report=document.createElement('div')
    report.style.cssText='position:fixed;left:0;top:0;width:794px;min-height:1123px;background:#fff;color:#111;padding:30px;z-index:2147483647;font-family:Arial,sans-serif;box-sizing:border-box;'
    report.innerHTML=`<style>
      .pdf-report *{box-sizing:border-box}.pdf-report h1{margin:0 0 5px;font-size:25px}.pdf-report h2{margin:0 0 20px;font-size:18px;color:#444}.pdf-report h3{margin:24px 0 8px;font-size:17px}.pdf-report table{width:100%;border-collapse:collapse;font-size:12px}.pdf-report th,.pdf-report td{border:1px solid #cbd5e1;padding:7px;text-align:left}.pdf-report th{background:#ffedd5;color:#7c2d12}.pdf-report .average{margin-top:12px;padding:10px;background:#fff7ed;border:1px solid #fdba74;font-weight:700}.pdf-report .empty{padding:18px;border:1px solid #ddd;background:#fafafa}.pdf-report svg{display:block;background:#fff}
    </style><div class="pdf-report"><h1>Fen Deneme Sonuç Raporu</h1><h2>${escapeHtml(selected.fullName)}</h2><table><thead><tr><th>#</th><th>Tür</th><th>Deneme</th><th>Doğru</th><th>Yanlış</th><th>Boş</th><th>Net</th><th>Okul Sırası</th></tr></thead><tbody>${rows||'<tr><td colspan="8">Henüz deneme sonucu bulunmuyor.</td></tr>'}</tbody></table>${averages?`<div class="average">Ortalama net: ${averages.net.toFixed(2)}</div>`:''}<h3>Son 10 Denemenin Net Grafiği</h3>${chartHtml}</div>`
    document.body.appendChild(report)
    try{
      const html2pdf=(await import('html2pdf.js')).default
      await new Promise(resolve=>setTimeout(resolve,150))
      await html2pdf().set({margin:7,filename:`${selected.fullName.replace(/\s+/g,'_')}_fen_deneme_raporu.pdf`,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true,backgroundColor:'#ffffff',logging:false},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css','legacy']}}).from(report).save()
    }catch(error){console.error(error);alert('PDF oluşturulamadı. Lütfen tekrar deneyin.')}finally{report.remove()}
  }

  const entries=Object.entries(selected?.lessons||{})
  const summary=useMemo(()=>{const done=entries.filter(([,x])=>x.status==='done');const paid=done.filter(([,x])=>x.payment==='paid');const unpaid=done.filter(([,x])=>x.payment!=='paid');const minutesOf=list=>list.reduce((sum,[,x])=>sum+Number(x.durationMinutes||selected?.lessonMinutes||60),0);const doneMinutes=minutesOf(done),paidMinutes=minutesOf(paid),unpaidMinutes=minutesOf(unpaid);const hourly=Number(selected?.hourlyFee||0);const paidFee=hourly*paidMinutes/60,unpaidFee=hourly*unpaidMinutes/60;return{doneMinutes,paidFee,unpaidFee,debt:unpaidFee}},[selected,entries])
  const first=new Date(month.getFullYear(),month.getMonth(),1),last=new Date(month.getFullYear(),month.getMonth()+1,0),start=(first.getDay()+6)%7
  const calendar=[...Array(start).fill(null),...Array.from({length:last.getDate()},(_,i)=>new Date(month.getFullYear(),month.getMonth(),i+1))]
  const activePool=exams.filter(e=>Boolean(e.archived)===showArchive)
  const assignments=(selected?.examAssignments||[]).filter(a=>Boolean(a.archived)===showArchive).sort(sortDate)
  const schoolExams=[...(selected?.schoolExams||[])].sort(sortDate)
  const onlineResults=(selected?.examAssignments||[]).filter(a=>a.result).map(a=>{const exam=exams.find(e=>e.id===a.examId);return{id:a.id,type:'Online',name:exam?.name||'Silinmiş deneme',date:a.finishedAt||a.endAt||a.createdAt,...resultValues(a.result),answers:a.answers||{},answerKey:exam?.answers||{}}})
  const allResults=[...onlineResults,...schoolExams.map(x=>({id:x.id,type:'Okul',name:x.name,date:x.date,correct:numeric(x.correct),wrong:numeric(x.wrong),blank:numeric(x.blank),net:Number(x.net),schoolRank:numeric(x.schoolRank)}))].sort(sortDate)
  const averages=allResults.length?{correct:allResults.reduce((s,x)=>s+x.correct,0)/allResults.length,wrong:allResults.reduce((s,x)=>s+x.wrong,0)/allResults.length,blank:allResults.reduce((s,x)=>s+x.blank,0)/allResults.length,net:allResults.reduce((s,x)=>s+x.net,0)/allResults.length}:null
  const lastTen=allResults.slice(-10)

  if(!ready||!poolReady)return <Box sx={{p:3}}><Typography>Yükleniyor…</Typography></Box>
  return <Box sx={{p:{xs:1.25,md:2}}}>
    <Stack spacing={2}>
      <Paper className="glass" sx={{p:2,borderRadius:3}}>
        <Stack direction={{xs:'column',sm:'row'}} spacing={1} alignItems={{sm:'center'}} justifyContent="space-between"><Box><Typography variant="h5" fontWeight={950}>Özel Ders Öğrencileri</Typography><Typography variant="body2" color="text.secondary">Öğrenciler yukarıda; seçilen öğrencinin tüm bilgileri sayfanın tamamında görünür.</Typography></Box><Button variant="contained" startIcon={<PersonAdd/>} onClick={openNew}>Öğrenci Ekle</Button></Stack>
        {students.length===0?<Alert severity="info" sx={{mt:2}}>Henüz özel ders öğrencisi eklenmedi.</Alert>:<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,minmax(0,1fr))',md:'repeat(3,minmax(0,1fr))',xl:'repeat(4,minmax(0,1fr))'},gap:1.25,mt:2}}>{students.map(student=><Paper key={student.id} variant="outlined" onClick={()=>{setSelectedId(student.id);setTab(0)}} sx={{p:1.4,borderRadius:3,cursor:'pointer',borderWidth:selected?.id===student.id?3:1,borderColor:selected?.id===student.id?'#c2410c':'divider',bgcolor:selected?.id===student.id?'#f97316 !important':'transparent',color:selected?.id===student.id?'#fff':'inherit',boxShadow:selected?.id===student.id?'0 5px 16px rgba(194,65,12,.35)':'none','& .MuiTypography-root':{color:selected?.id===student.id?'#fff':undefined},'& .MuiIconButton-root':{color:selected?.id===student.id?'#fff':undefined}}}><Stack direction="row" spacing={1} alignItems="center"><Box sx={{flex:1,minWidth:0}}><Typography fontWeight={950} noWrap>{student.fullName}</Typography><Typography variant="caption" color="text.secondary" noWrap>@{student.username||'kullanıcı adı yok'}</Typography></Box><IconButton size="small" aria-label="Düzenle" onClick={e=>{e.stopPropagation();openEditStudent(student)}}><Edit fontSize="small"/></IconButton><IconButton size="small" color="error" aria-label="Sil" onClick={e=>{e.stopPropagation();removeStudent(student)}}><DeleteOutline fontSize="small"/></IconButton></Stack></Paper>)}</Box>}
      </Paper>

      <Paper className="glass" sx={{p:2,borderRadius:3}}>
        <Stack direction={{xs:'column',md:'row'}} spacing={1} justifyContent="space-between" alignItems={{md:'center'}}><Box><Typography variant="h6" fontWeight={950}>Fen Deneme Havuzu</Typography><Typography variant="body2" color="text.secondary">Denemeyi bir kez hazırla, öğrenci profilinden tarih ve saat seçerek ata.</Typography></Box><Stack direction="row" spacing={1}><Button variant="outlined" startIcon={showArchive?<Restore/>:<Archive/>} onClick={()=>setShowArchive(v=>!v)}>{showArchive?'Aktifleri Göster':'Arşivi Göster'}</Button><Button variant="contained" startIcon={<Science/>} onClick={openNewExam}>Deneme Oluştur</Button></Stack></Stack>
        <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(2,minmax(0,1fr))'},gap:1.25,mt:2}}>{activePool.length===0?<Alert severity="info">Bu bölümde deneme yok.</Alert>:activePool.map(exam=><Paper key={exam.id} variant="outlined" sx={{p:1.5,borderRadius:3}}><Stack direction="row" spacing={1} alignItems="center"><Box sx={{flex:1,minWidth:0}}><Typography fontWeight={950} noWrap>{exam.name}</Typography><Typography variant="caption" color="text.secondary">20 soru {exam.attachment?'• Dosya yüklü':'• Dosya yok'}</Typography></Box><Button size="small" onClick={()=>openEditExam(exam)}>Düzenle</Button><IconButton onClick={()=>archiveExam(exam)}>{exam.archived?<Restore/>:<Archive/>}</IconButton><IconButton color="error" onClick={()=>deleteExam(exam)}><DeleteOutline/></IconButton></Stack></Paper>)}</Box>
      </Paper>

      {!selected?<Alert severity="info">Detayları görmek için bir öğrenci seç.</Alert>:<Paper className="glass" variant="outlined" sx={{p:0,borderRadius:3,overflow:'hidden',borderWidth:2,borderColor:'#f59e0b'}}>
        <Box sx={{p:2,'& .MuiPaper-outlined':{borderColor:'#f59e0b'}}}><Stack direction={{xs:'column',md:'row'}} spacing={1} alignItems={{md:'center'}} justifyContent="space-between"><Box><Typography variant="h5" fontWeight={950}>{selected.fullName}</Typography><Typography variant="body2" color="text.secondary">Kullanıcı adı: {selected.username||'—'} {selected.address?`• ${selected.address}`:''}</Typography></Box><Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<PictureAsPdf/>} onClick={exportPdf}>Tüm Sonuçları PDF Al</Button></Stack></Stack></Box>
        <Divider/>
        <Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" scrollButtons="auto"><Tab label="Takvim ve Ücret"/><Tab label="Online Denemeler"/><Tab label="Okul Denemeleri"/><Tab label="Analiz"/></Tabs>
        <Box sx={{p:2}}>
          {tab===0&&<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'280px minmax(0,1fr)'},gap:2,alignItems:'start','& .MuiPaper-outlined':{borderColor:'#f59e0b'}}}><Stack spacing={1.25}><Paper variant="outlined" sx={{p:1.5,borderRadius:3}}><Typography variant="caption">Yapılan ders saati</Typography><Typography variant="h6" fontWeight={950}>{(summary.doneMinutes/60).toFixed(2)} saat</Typography></Paper><Paper variant="outlined" sx={{p:1.5,borderRadius:3}}><Typography variant="caption">Ödenen ders ücreti</Typography><Typography variant="h6" fontWeight={950}>{money(summary.paidFee)}</Typography></Paper><Paper variant="outlined" sx={{p:1.5,borderRadius:3}}><Typography variant="caption">Ödenmeyen ders ücreti</Typography><Typography variant="h6" fontWeight={950}>{money(summary.unpaidFee)}</Typography></Paper><Paper variant="outlined" sx={{p:1.5,borderRadius:3,bgcolor:'rgba(245,158,11,.10)'}}><Typography variant="caption">Toplam borç</Typography><Typography variant="h6" fontWeight={950}>{money(summary.debt)}</Typography></Paper></Stack><Paper variant="outlined" sx={{p:2,borderRadius:3}}><Stack direction="row" justifyContent="space-between" alignItems="center"><IconButton onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ArrowBack/></IconButton><Typography variant="h6" fontWeight={950}>{month.toLocaleDateString('tr-TR',{month:'long',year:'numeric'})}</Typography><IconButton onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ArrowForward/></IconButton></Stack><Box sx={{display:'grid',gridTemplateColumns:'repeat(7,1fr)',gap:.6,mt:1}}>{['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'].map(x=><Typography key={x} align="center" variant="caption" fontWeight={900}>{x}</Typography>)}{calendar.map((d,i)=>{if(!d)return <Box key={`blank-${i}`}/>;const key=dateKey(d),rec=selected.lessons?.[key],st=rec?statuses[rec.status]:null;return <Button key={key} onClick={()=>openDay(key)} variant='outlined' sx={{minWidth:0,height:72,borderRadius:2,flexDirection:'column',bgcolor:rec?`${st?.bg} !important`:undefined,color:rec?`${st?.color} !important`:undefined,borderColor:rec?`${st?.border} !important`:undefined,borderWidth:rec?2:1,'&:hover':rec?{bgcolor:`${st.bg} !important`,filter:'brightness(.98)'}:{}}}><b>{d.getDate()}</b>{rec&&<><small style={{fontWeight:900,lineHeight:1.1}}>{st.label}</small><small style={{fontWeight:800,lineHeight:1.1}}>{rec.payment==='paid'?'Ödendi':'Ödenmedi'}</small></>}</Button>})}</Box></Paper></Box>}

          {tab===1&&<Paper variant="outlined" sx={{p:2,borderRadius:3}}><Stack direction={{xs:'column',sm:'row'}} spacing={1} justifyContent="space-between" sx={{mb:2}}><Box><Typography variant="h6" fontWeight={950}>Online Denemeler</Typography><Typography variant="body2" color="text.secondary">Atanan denemeleri düzenle, sil, sonucu gör veya sonucu iptal ederek tekrar aktif et.</Typography></Box><Button variant="contained" startIcon={<AssignmentTurnedIn/>} onClick={openAssign}>Deneme Ata</Button></Stack>{assignments.length===0?<Alert severity="info">Bu bölümde deneme yok.</Alert>:<Stack spacing={1.25}>{assignments.map(a=>{const e=exams.find(x=>x.id===a.examId);return <Paper key={a.id} variant="outlined" sx={{p:1.5,borderRadius:3}}><Stack direction={{xs:'column',lg:'row'}} spacing={1} alignItems={{lg:'center'}}><Box sx={{flex:1}}><Typography fontWeight={950}>{e?.name||'Silinmiş deneme'}</Typography><Typography variant="body2" color="text.secondary">{fmtDate(a.startAt)} – {fmtDate(a.endAt)}</Typography></Box><Chip label={a.result?'Tamamlandı':a.status==='active'?'Aktif':'Bekliyor'} color={a.result?'success':'info'}/><Button size="small" startIcon={<Edit/>} onClick={()=>editAssignment(a)}>Düzenle</Button><Button size="small" color="error" startIcon={<DeleteOutline/>} onClick={()=>deleteAssignment(a)}>Sil</Button>{a.result&&<Button size="small" startIcon={<Visibility/>} onClick={()=>showResult(a)}>Sonucu Gör</Button>}{a.result&&<Button size="small" color="warning" onClick={()=>cancelResult(a)}>İptal Et</Button>}<Button size="small" startIcon={a.archived?<Restore/>:<Archive/>} onClick={()=>archiveAssignment(a)}>{a.archived?'Geri Al':'Arşivle'}</Button></Stack></Paper>})}</Stack>}</Paper>}

          {tab===2&&<Paper variant="outlined" sx={{p:2,borderRadius:3}}><Stack direction={{xs:'column',sm:'row'}} spacing={1} justifyContent="space-between" sx={{mb:2}}><Box><Typography variant="h6" fontWeight={950}>Okul Denemeleri – Fen</Typography><Typography variant="body2" color="text.secondary">Deneme adı, tarih, doğru, yanlış, net ve okul sırası elle girilir.</Typography></Box><Button variant="contained" startIcon={<School/>} onClick={()=>openSchool()}>Sonuç Ekle</Button></Stack>{schoolExams.length===0?<Alert severity="info">Henüz okul denemesi eklenmedi.</Alert>:<Stack spacing={1}>{schoolExams.map(x=><Paper key={x.id} variant="outlined" sx={{p:1.5,borderRadius:3}}><Stack direction={{xs:'column',md:'row'}} spacing={1} alignItems={{md:'center'}}><Box sx={{flex:1}}><Typography fontWeight={950}>{x.name}</Typography><Typography variant="caption" color="text.secondary">{new Date(`${x.date}T12:00:00`).toLocaleDateString('tr-TR')}</Typography></Box><Chip label={`${x.correct} D • ${x.wrong} Y`}/><Chip color="primary" label={`${Number(x.net).toFixed(2)} net`}/><Chip color="secondary" label={`Okul sırası: ${x.schoolRank||'—'}`}/><Button size="small" onClick={()=>openSchool(x)}>Düzenle</Button><IconButton color="error" onClick={()=>deleteSchool(x.id)}><DeleteOutline/></IconButton></Stack></Paper>)}</Stack>}</Paper>}

          {tab===3&&<Stack spacing={2}><Paper variant="outlined" sx={{p:2,borderRadius:3}}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" spacing={1}><Box><Typography variant="h6" fontWeight={950}>Tüm Deneme Sonuçları</Typography><Typography variant="body2" color="text.secondary">İlk deneme üstte, sonraki denemeler altta tarih sırasına göre gösterilir.</Typography></Box><Stack direction="row" spacing={1}><Chip sx={{bgcolor:'#16a34a',color:'#fff',fontWeight:900}} label="Doğru"/><Chip sx={{bgcolor:'#dc2626',color:'#fff',fontWeight:900}} label="Yanlış"/><Chip sx={{bgcolor:'#f59e0b',color:'#fff',fontWeight:900}} label="Boş"/></Stack></Stack><Divider sx={{my:2}}/>{allResults.length===0?<Alert severity="info">Henüz tamamlanmış deneme sonucu yok.</Alert>:<Stack spacing={1}>{allResults.map((x,i)=><Paper key={`${x.type}-${x.id}`} variant="outlined" sx={{p:1.5,borderRadius:3}}><Stack direction={{xs:'column',md:'row'}} spacing={1} alignItems={{md:'center'}}><Box sx={{flex:1}}><Typography fontWeight={950}>{i+1}. {x.name}</Typography><Typography variant="caption" color="text.secondary">{x.type} • {new Date(x.date).toLocaleDateString('tr-TR')}</Typography></Box><Chip sx={{bgcolor:'#16a34a',color:'#fff'}} label={`${x.correct.toFixed(0)} Doğru`}/><Chip sx={{bgcolor:'#dc2626',color:'#fff'}} label={`${x.wrong.toFixed(0)} Yanlış`}/><Chip sx={{bgcolor:'#f59e0b',color:'#fff'}} label={`${x.blank.toFixed(0)} Boş`}/><Chip color="primary" label={`${x.net.toFixed(2)} Net`}/>{x.type==='Okul'&&<Chip color="secondary" label={`Okul: ${x.schoolRank||'—'}`}/>}</Stack>{x.type==='Online'&&Object.keys(x.answerKey||{}).length>0&&<Box sx={{display:'grid',gridTemplateColumns:'repeat(10,minmax(30px,1fr))',gap:.5,mt:1.25}}>{Array.from({length:20},(_,q)=>q+1).map(q=>{const given=x.answers?.[q]||x.answers?.[String(q)]||'';const key=x.answerKey?.[q]||x.answerKey?.[String(q)]||'';const state=!given?'blank':given===key?'correct':'wrong';const bg=state==='correct'?'#16a34a':state==='wrong'?'#dc2626':'#f59e0b';return <Box key={q} title={`${q}. soru: ${given||'Boş'} / ${key}`} sx={{bgcolor:bg,color:'#fff',borderRadius:1,textAlign:'center',py:.5,fontWeight:900,fontSize:12}}>{q}</Box>})}</Box>}</Paper>)}<Paper sx={{p:1.5,borderRadius:3,bgcolor:'action.hover'}}><Stack direction={{xs:'column',sm:'row'}} spacing={1} alignItems={{sm:'center'}}><Typography fontWeight={950} sx={{flex:1}}>Ortalama</Typography><Chip label={`${averages.correct.toFixed(2)} Doğru`}/><Chip label={`${averages.wrong.toFixed(2)} Yanlış`}/><Chip label={`${averages.blank.toFixed(2)} Boş`}/><Chip color="primary" label={`${averages.net.toFixed(2)} Net`}/></Stack></Paper></Stack>}</Paper><Paper variant="outlined" sx={{p:2,borderRadius:3}}><Typography variant="h6" fontWeight={950}>Son 10 Denemenin Net Grafiği</Typography><Typography variant="body2" color="text.secondary" sx={{mb:1}}>Online ve okul denemeleri birlikte değerlendirilir.</Typography><NetLineChart items={lastTen}/></Paper></Stack>}
        </Box>
      </Paper>}
    </Stack>



    <Dialog open={formOpen} onClose={()=>setFormOpen(false)} fullWidth maxWidth="sm"><DialogTitle fontWeight={950}>{form.id?'Öğrenciyi Düzenle':'Özel Ders Öğrencisi Ekle'}</DialogTitle><DialogContent><Stack spacing={2} sx={{mt:1}}><TextField required label="Ad Soyad" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/><TextField required label="Kullanıcı adı" value={form.username||''} onChange={e=>setForm({...form,username:e.target.value})}/><TextField required label="Şifre" value={form.password||''} onChange={e=>setForm({...form,password:e.target.value})}/><TextField label="Adres (zorunlu değil)" multiline minRows={2} value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/><TextField label="Saatlik ders ücreti (TL)" type="number" value={form.hourlyFee} onChange={e=>setForm({...form,hourlyFee:e.target.value})}/><TextField select label="Varsayılan ders süresi" value={form.lessonMinutes||60} onChange={e=>setForm({...form,lessonMinutes:Number(e.target.value)})}>{[40,60,80,90,120].map(x=><MenuItem key={x} value={x}>{x} dakika</MenuItem>)}</TextField></Stack></DialogContent><DialogActions><Button onClick={()=>setFormOpen(false)}>Vazgeç</Button><Button variant="contained" startIcon={<Save/>} onClick={saveStudent}>Kaydet</Button></DialogActions></Dialog>
    <Dialog open={dayOpen} onClose={()=>setDayOpen(false)} fullWidth maxWidth="xs"><DialogTitle fontWeight={950}>{selectedDate&&new Date(`${selectedDate}T12:00:00`).toLocaleDateString('tr-TR')}</DialogTitle><DialogContent><Stack spacing={2} sx={{mt:1}}><TextField select label="Ders durumu" value={entry.status} onChange={e=>setEntry({...entry,status:e.target.value})}>{Object.entries(statuses).map(([k,v])=><MenuItem key={k} value={k}>{v.label}</MenuItem>)}</TextField><TextField select label="Ödeme durumu" value={entry.payment} onChange={e=>setEntry({...entry,payment:e.target.value})}><MenuItem value="paid">Ödendi</MenuItem><MenuItem value="unpaid">Ödenmedi</MenuItem></TextField><TextField type="number" label="Ders süresi (dakika)" value={entry.durationMinutes} onChange={e=>setEntry({...entry,durationMinutes:e.target.value})}/><TextField multiline minRows={2} label="Ders notu / ödev" value={entry.note||''} onChange={e=>setEntry({...entry,note:e.target.value})}/></Stack></DialogContent><DialogActions><Button color="error" onClick={deleteDay}>Kaydı Sil</Button><Box sx={{flex:1}}/><Button onClick={()=>setDayOpen(false)}>Vazgeç</Button><Button variant="contained" onClick={saveDay}>Kaydet</Button></DialogActions></Dialog>
    <Dialog open={examOpen} onClose={()=>setExamOpen(false)} fullWidth maxWidth="md"><DialogTitle fontWeight={950}>{examForm.id?'Denemeyi Düzenle':'Fen Denemesi Oluştur'}</DialogTitle><DialogContent dividers><Stack spacing={2} sx={{pt:1}}><TextField label="Deneme adı" value={examForm.name} onChange={e=>setExamForm({...examForm,name:e.target.value})}/><Paper variant="outlined" sx={{p:2,borderRadius:3}}><Typography fontWeight={900}>Deneme Dosyası (isteğe bağlı)</Typography><Typography variant="body2" color="text.secondary" sx={{mb:1}}>PDF, JPG, PNG veya WEBP • En fazla 20 MB</Typography><Button component="label" variant="outlined" startIcon={<UploadFile/>}>{examFile?.name||examForm.attachment?.name||'Dosya Seç'}<input hidden type="file" accept={ONLINE_EXAM_ACCEPT} onChange={e=>setExamFile(e.target.files?.[0]||null)}/></Button></Paper><Typography variant="h6" fontWeight={950}>20 Soruluk Cevap Anahtarı</Typography><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1fr 1fr'},gap:2}}>{[1,11].map(start=><Stack key={start} spacing={1}>{Array.from({length:10},(_,i)=>start+i).map(q=><Paper key={q} variant="outlined" sx={{p:.75,display:'grid',gridTemplateColumns:'32px repeat(4,1fr)',gap:.5,alignItems:'center'}}><b>{q}</b>{ANSWERS.map(a=><Button key={a} size="small" variant={examForm.answers?.[q]===a?'contained':'outlined'} onClick={()=>setExamForm({...examForm,answers:{...(examForm.answers||{}),[q]:a}})}>{a}</Button>)}</Paper>)}</Stack>)}</Box></Stack></DialogContent><DialogActions><Button onClick={()=>setExamOpen(false)}>Vazgeç</Button><Button variant="contained" disabled={examUploading} onClick={saveExam}>{examUploading?'Yükleniyor…':'Kaydet'}</Button></DialogActions></Dialog>
    <Dialog open={assignOpen} onClose={()=>setAssignOpen(false)} fullWidth maxWidth="sm"><DialogTitle fontWeight={950}>{assignForm.assignmentId?'Deneme Atamasını Düzenle':'Deneme Ata'}</DialogTitle><DialogContent><Stack spacing={2} sx={{mt:1}}><TextField select label="Deneme" value={assignForm.examId} onChange={e=>setAssignForm({...assignForm,examId:e.target.value})}>{exams.filter(e=>!e.archived).map(e=><MenuItem key={e.id} value={e.id}>{e.name}</MenuItem>)}</TextField><TextField type="datetime-local" label="Başlangıç" value={assignForm.startAt} onChange={e=>setAssignForm({...assignForm,startAt:e.target.value})} InputLabelProps={{shrink:true}}/><TextField type="datetime-local" label="Bitiş" value={assignForm.endAt} onChange={e=>setAssignForm({...assignForm,endAt:e.target.value})} InputLabelProps={{shrink:true}}/></Stack></DialogContent><DialogActions><Button onClick={()=>setAssignOpen(false)}>Vazgeç</Button><Button variant="contained" onClick={assignForm.assignmentId?saveAssignmentEdit:assignExam}>{assignForm.assignmentId?'Kaydet':'Öğrenciye Gönder'}</Button></DialogActions></Dialog>
    <Dialog open={resultOpen} onClose={()=>setResultOpen(false)} fullWidth maxWidth="sm"><DialogTitle fontWeight={950}>Online Deneme Sonucu</DialogTitle><DialogContent>{resultAssignment&&(()=>{const e=exams.find(x=>x.id===resultAssignment.examId);const r=resultValues(resultAssignment.result);return <Stack spacing={2} sx={{mt:1}}><Typography variant="h6" fontWeight={950}>{e?.name||'Deneme'}</Typography><Stack direction="row" spacing={1} flexWrap="wrap"><Chip sx={{bgcolor:'#16a34a',color:'#fff'}} label={`${r.correct} Doğru`}/><Chip sx={{bgcolor:'#dc2626',color:'#fff'}} label={`${r.wrong} Yanlış`}/><Chip sx={{bgcolor:'#f59e0b',color:'#fff'}} label={`${r.blank} Boş`}/><Chip color="primary" label={`${r.net.toFixed(2)} Net`}/></Stack><Box sx={{display:'grid',gridTemplateColumns:'repeat(10,1fr)',gap:.6}}>{Array.from({length:20},(_,i)=>i+1).map(q=>{const given=resultAssignment.answers?.[q]||resultAssignment.answers?.[String(q)]||'';const key=e?.answers?.[q]||e?.answers?.[String(q)]||'';const bg=!given?'#f59e0b':given===key?'#16a34a':'#dc2626';return <Box key={q} sx={{bgcolor:bg,color:'#fff',borderRadius:1,p:.7,textAlign:'center',fontWeight:950}}>{q}</Box>})}</Box></Stack>})()}</DialogContent><DialogActions><Button onClick={()=>setResultOpen(false)}>Kapat</Button></DialogActions></Dialog>
    <Dialog open={schoolOpen} onClose={()=>setSchoolOpen(false)} fullWidth maxWidth="sm"><DialogTitle fontWeight={950}>{schoolForm.id?'Okul Denemesini Düzenle':'Okul Denemesi Fen Sonucu'}</DialogTitle><DialogContent><Stack spacing={2} sx={{mt:1}}><TextField label="Deneme adı" value={schoolForm.name} onChange={e=>setSchoolForm({...schoolForm,name:e.target.value})}/><TextField type="date" label="Tarih" value={schoolForm.date} onChange={e=>setSchoolForm({...schoolForm,date:e.target.value})} InputLabelProps={{shrink:true}}/><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,1fr)'},gap:1}}><TextField type="number" label="Doğru" value={schoolForm.correct} onChange={e=>setSchoolForm({...schoolForm,correct:e.target.value})}/><TextField type="number" label="Yanlış" value={schoolForm.wrong} onChange={e=>setSchoolForm({...schoolForm,wrong:e.target.value})}/><TextField type="number" label="Net" value={schoolForm.net} helperText="Boş bırakırsan otomatik hesaplanır" onChange={e=>setSchoolForm({...schoolForm,net:e.target.value})}/><TextField type="number" label="Okul sırası" value={schoolForm.schoolRank} onChange={e=>setSchoolForm({...schoolForm,schoolRank:e.target.value})}/></Box></Stack></DialogContent><DialogActions><Button onClick={()=>setSchoolOpen(false)}>Vazgeç</Button><Button variant="contained" onClick={saveSchool}>Kaydet</Button></DialogActions></Dialog>
  </Box>
}
